// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avsuyudchzyoyakxotfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2c3V5dWRjaHp5b3lha3hvdGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODQxNDUsImV4cCI6MjA3NDY2MDE0NX0._oyWwykNCIhE8m2ALlMRTEj7chQ4ak0sxde1gN6ILsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});